### ISSUE TITLE
Device address not set after AT+JOIN

### ISSUE THREAD

**Issue by jpbaltazar** [hardwario/lora-modem#143]
I've observed the communications of the gateway with the device address set to 00000000 after successfully joining the network.

Flashing the device with version 1.3.2, the issue does not present itself.

The device is in OTAA mode.

**Comment by janakj** [comment]
I have tested this extensively on my side over the last couple of days, and I cannot reproduce this behavior. The DevAddr is always correctly set to a non-zero value on my devices. I don't do any DevAddr-specific processing in the firmware and also have not changed any of the code paths since 1.3.2 (https://github.com/hardwario/lora-modem/compare/v1.3.2...main). The value is managed by LoRaMac-node. The AT+DEVADDR setter/getter only reads/writes the value in LoRaMac-node internal data structures.

Also, if the firmware finds a 00000000 DevAddr in EEPROM, it generates a random value instead. This is mainly used in the ABP mode. In OTAA mode, the correct DevAddr is generated during Join.

I will work on releasing 1.4.0 now, including the polling mode. If you have time, please test that version, but do a factory reset after you have flashed it. If you still have the same issue, please feel free to reopen this issue.
